/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`test/parser-asserts.js TAP a stream of parser-asserts > got expected events 1`] = `
[ [ 'assert',
    { ok: true,
      id: 1,
      name: 'this is fine',
      time: null,
      diag: undefined } ],
  [ 'pass',
    { ok: true,
      id: 1,
      name: 'this is fine',
      time: null,
      diag: undefined } ],
  [ 'assert',
    { ok: false,
      id: 1,
      name: 'child test > not so fine',
      diag: { at: {}, stack: null, source: "tt.fail('not so fine')\\n" },
      time: null } ],
  [ 'fail',
    { ok: false,
      id: 1,
      name: 'child test > not so fine',
      diag: { at: {}, stack: null, source: "tt.fail('not so fine')\\n" },
      time: null } ],
  [ 'assert',
    { ok: false,
      id: 2,
      todo: 'will do later',
      name: 'child test > expect truthy value',
      diag:
       { at: {},
         source: "tt.ok(false, { todo: 'will do later' })\\n",
         stack: null },
      time: null } ],
  [ 'todo',
    { ok: false,
      id: 2,
      todo: 'will do later',
      name: 'child test > expect truthy value',
      diag:
       { at: {},
         source: "tt.ok(false, { todo: 'will do later' })\\n",
         stack: null },
      time: null } ],
  [ 'assert',
    { ok: false,
      id: 3,
      skip: 'skip this',
      name: 'child test > expect truthy value',
      time: null,
      diag: undefined } ],
  [ 'skip',
    { ok: false,
      id: 3,
      skip: 'skip this',
      name: 'child test > expect truthy value',
      time: null,
      diag: undefined } ],
  [ 'assert',
    { ok: false,
      id: 1,
      name: 'lying child > lying',
      time: null,
      diag: undefined } ],
  [ 'fail',
    { ok: false,
      id: 1,
      name: 'lying child > lying',
      time: null,
      diag: undefined } ],
  [ 'assert',
    { ok: true,
      id: 2,
      name: 'lying child >',
      time: null,
      diag: undefined } ],
  [ 'pass',
    { ok: true,
      id: 2,
      name: 'lying child >',
      time: null,
      diag: undefined } ],
  [ 'assert',
    { ok: true,
      id: 1,
      name: 'lying child > this is fine',
      time: null,
      diag: undefined } ],
  [ 'pass',
    { ok: true,
      id: 1,
      name: 'lying child > this is fine',
      time: null,
      diag: undefined } ],
  [ 'assert',
    { ok: true,
      id: 3,
      time: null,
      name: 'lying child',
      diag: undefined } ],
  [ 'pass',
    { ok: true,
      id: 3,
      time: null,
      name: 'lying child',
      diag: undefined } ],
  [ 'assert',
    { ok: true,
      id: 4,
      todo: true,
      name: 'todo test',
      time: null,
      diag: undefined } ],
  [ 'todo',
    { ok: true,
      id: 4,
      todo: true,
      name: 'todo test',
      time: null,
      diag: undefined } ],
  [ 'assert',
    { ok: true,
      id: 5,
      skip: true,
      name: 'skip test',
      time: null,
      diag: undefined } ],
  [ 'skip',
    { ok: true,
      id: 5,
      skip: true,
      name: 'skip test',
      time: null,
      diag: undefined } ] ]
`
